### ISSUE TITLE
Semgrep patterns failing on 2.10.1

### ISSUE THREAD

**Issue by Piccirello** [coinbase/salus#142]
Salus appears to call semgrep with the `--strict` flag as of 2.10.1. This has resulted in our Semgrep patterns failing with a parse error (semgrep exit code 3). What's odd if that these patterns work as expected when semgrep is called directly. It's also worth noting that we use Salus via the `federacy/scan-action` GitHub Action.

Manual run with one pattern:
```sh
$ semgrep --version
0.10.1
$ semgrep --strict --json --pattern "req.body" --lang javascript --exclude-dir node_modules --exclude-dir bower_components --exclude-dir express .
{"results": [], "errors": []}
$ echo $?
0
```

Relevant section from salus-config.yml:
```yaml
scanner_configs:
  Semgrep:
    matches:
      - pattern: eval(...)
        message: Eval is Evil
        language: javascript
        forbidden: true
        exclude_directory:
          - node_modules
          - bower_components
      - pattern: req.body
        message: Use req.validated.body
        language: javascript
        forbidden: true
        exclude_directory:
          - node_modules
          - bower_components
          - express
      - pattern: req.params
        message: Use req.validated.url
        language: javascript
        forbidden: true
        exclude_directory:
          - node_modules
          - bower_components
          - express
      - pattern: req.query
        message: Use req.validated.query
        language: javascript
        forbidden: true
        exclude_directory:
          - node_modules
          - bower_components
          - express
```

Salus error:
 ```
 ~~ Errors:

  [
    {
      "status": 3,
      "stderr": "parse error ",
      "message": "Call to semgrep failed"
    },
    {
      "status": 3,
      "stderr": "parse error ",
      "message": "Call to semgrep failed"
    },
    {
      "status": 3,
      "stderr": "parse error ",
      "message": "Call to semgrep failed"
    },
    {
      "status": 3,
      "stderr": "parse error ",
      "message": "Call to semgrep failed"
    }
  ]
```
