### ISSUE TITLE
SARIF support

### ISSUE THREAD

**Issue by kiwiz** [coinbase/salus#236]
A number of scanners that Salus comes with include [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html) support. I'm hoping to send these results to Github's Code Scanning dashboard, so that we have a consistent way of reviewing code quality issues.

I don't think there's currently a way to expose this yet - is there interest in a PR & any suggestions on how to expose this option?

**Comment by nishils** [comment]
I love this idea and have talked to the team internally about it.

I think the way we would approach this is by adding an option in the reports yaml file and then 

```
reports:
  - uri: file://tests/salus-report.txt
    format: txt
  - uri: https://salus-config.internal.net/salus-report
    format: json
    verbose: true
  - format: sarif # this is the option that needs to be built
```

In scanners that already support SARIF, we would simply need to pass this as an argument to the scanner which is pretty straightforward to do. However for scanners that don't have SARIF support, we'd need to build some conversion layer.

1. We need to first by adding an option to https://github.com/coinbase/salus/blob/master/lib/salus/report.rb to add this report format (and make sure that the configuration is read from the yaml file as suggested above).

2. If the scanner support SARIF, delegate to the scanner via the scanner report to output SARIF.

3. If the scanner does not support SARIF, build a function in at the scanner level. SARIF helper functions could probably be isolated to a module.

This is just me roughly sketching out how we could add support. 

@xolaz or @ghbren ^
