### ISSUE TITLE
Salus exception config not working with Circle CI

### ISSUE THREAD

**Issue by iondrimba** [coinbase/salus#243]
I'm currently experiencing this issue where my build is failing because of two npm audit problems.

https://www.npmjs.com/advisories/1179
https://www.npmjs.com/advisories/1556

It was working today.

```
scanner_configs:
  NPMAudit:
    exceptions:
      - advisory_id: 1179
        changed_by: john@example.com
        notes: https://www.npmjs.com/advisories/1179
      - advisory_id: 1556
        changed_by: john@example.com
        notes: https://www.npmjs.com/advisories/1556
```

![Screenshot from 2020-11-25 17-17-19](https://user-images.githubusercontent.com/178548/100277568-1add7480-2f42-11eb-9d47-a86aed6e9eef.png)
